export const AUTH_TYPES = {
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILED: "SIGN_IN_FAILED",

  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILED: "SIGN_UP_FAILED",
  SIGN_UP_RESET: "SIGN_UP_RESET",

  LOG_OUT_START: "LOG_OUT_START",
  LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
  LOG_OUT_FAILED: "LOG_OUT_FAILED",
};

export const PROFILE_TYPES = {
  COMPLETE_PROFILE_START: "COMPLETE_PROFILE_START",
  COMPLETE_PROFILE_SUCCESS: "COMPLETE_PROFILE_SUCCESS",
  COMPLETE_PROFILE_FAILED: "COMPLETE_PROFILE_FAILED",
};




export const POST_TYPES = {
  GET_POST_START: "GET_POST_START",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAILED: "GET_POST_FAILED",

  CREATE_POST_START: "CREATE_POST_START",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILED: "CREATE_POST_FAILED",

  UPDATE_POST_START: "UPDATE_POST_START",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILED: "UPDATE_POST_FAILED",

  DELETE_POST_START: "DELETE_POST_START",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILED: "DELETE_POST_FAILED",
  
  GET_NEW_POST_START: "GET_NEW_POST_START",
  GET_NEW_POST_SUCCESS: "GET_NEW_POST_SUCCESS",
  GET_NEW_POST_FAILED: "GET_NEW_POST_FAILED",
};
export const COMMENT_TYPES = {
  GET_COMMENT_START: "GET_COMMENT_START",
  GET_COMMENT_SUCCESS: "GET_COMMENT_SUCCESS",
  GET_COMMENT_FAILED: "GET_COMMENT_FAILED",

  CREATE_COMMENT_START: "CREATE_COMMENT_START",
  CREATE_COMMENT_SUCCESS: "CREATE_COMMENT_SUCCESS",
  CREATE_COMMENT_FAILED: "CREATE_COMMENT_FAILED",

  UPDATE_COMMENT_START: "UPDATE_COMMENT_START",
  UPDATE_COMMENT_SUCCESS: "UPDATE_COMMENT_SUCCESS",
  UPDATE_COMMENT_FAILED: "UPDATE_COMMENT_FAILED",

  DELETE_COMMENT_START: "DELETE_COMMENT_START",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAILED: "DELETE_COMMENT_FAILED",
};

export const STORY_TYPES = {
  GET_STORY_START: "GET_STORY_START",
  GET_STORY_SUCCESS: "GET_STORY_SUCCESS",
  GET_STORY_FAILED: "GET_STORY_FAILED",

  CREATE_STORY_START: "CREATE_STORY_START",
  CREATE_STORY_SUCCESS: "CREATE_STORY_SUCCESS",
  CREATE_STORY_FAILED: "CREATE_STORY_FAILED",

  UPDATE_STORY_START: "UPDATE_STORY_START",
  UPDATE_STORY_SUCCESS: "UPDATE_STORY_SUCCESS",
  UPDATE_STORY_FAILED: "UPDATE_STORY_FAILED",

  DELETE_STORY_START: "DELETE_STORY_START",
  DELETE_STORY_SUCCESS: "DELETE_STORY_SUCCESS",
  DELETE_STORY_FAILED: "DELETE_STORY_FAILED",

  GET_ASSETS_STORY_START: "GET_ASSETS_STORY_START",
  GET_ASSETS_STORY_SUCCESS: "GET_ASSETS_STORY_SUCCESS",
  GET_ASSETS_STORY_FAILED: "GET_ASSETS_STORY_FAILED",
};

export const ACCESS_TYPES = {
  GET_ACCESS_TYPES: "GET_ACCESS_TYPES",



};
export const LIKE_TYPES = {

  CREATE_LIKE_START: "CREATE_LIKE_START",
  CREATE_LIKE_SUCCESS: "CREATE_LIKE_SUCCESS",
  CREATE_LIKE_FAILED: "CREATE_LIKE_FAILED",


};